---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86132.
--- DateTime: 2024/11/12 下午1:24
---

local voucherId = ARGV[1]
local userId = ARGV[2]

local stockKey = 'seckill:stock' .. voucherId
local orderKey = 'seckill:order' .. voucherId

--此时库存不足
if(tonumber(redis.call('get',voucherKey) <= 0) )
    then return 1
end

--表示用户已经下单
if(redis.call('isnumber',orderKey,userId) == 1)
    then return 2
end

redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)
return 0